### PR TITLE
Add support for generating Windows executables with Launch4j

### PR DESCRIPTION
**Pull request by asarium**
This adds an Ant task which converts the compiled installer jar to a
native executable by wrapping the jar in that executable. This should
reduce user errors where Java is not associated correctly with the .jar
extension and it also displays a nice message if Java could not be
found.

I needed to change a few lines in the source since the code did not
compile with the options present in `build.xml`.

Before using this feature Launch4j has to be installed and the `launch4j.dir`
needs to be set to the installation directory of Launch4j for this to
work correctly.

### CODE REVIEW

**Comment by Goober5000** [comment]
This looks promising.  Looking at Launch4j was on my to-do list but if this PR takes care of the job, it will get implemented that much quicker.  I will review this ASAP.

**Comment by Goober5000** [comment]
Why did you remove the `@Override` annotations?

**Review by Goober5000 — COMMENTED** [review]
Why did you remove the `@Override` annotations?

**Comment by Goober5000** [comment]
Looks good in other respects.  Just installed Launch4J and tested it on my system and it works. :+1:

**Comment by asarium** [comment]
I removed the `@Override` because it wouldn't compile otherwise. An override on an interface implementation is not allowed in Java 1.5 and since that is what Ant call javac with it doesn't compile.

**Comment by Goober5000** [comment]
This is true; I'd forgotten about that.  I would always catch those when I compiled using my 1.5 VM, but for some reason, using the 1.8 VM with the 1.5 flag didn't catch that.

**Pull request merged**
